import awakened as aw, delve_Class as dc, skill as sk, timeline as tl

eric = aw.Awakened(name='Eric',attributes = [10, 10, 10, 10, 10, 10, 10, 10], level = 5, level_cap=21)
eric.date = eric.date.plus(tl.Duration(int(51.5*86400000)))
eric.set_class(dc.dynamo)
eric.add_experience(200000)
eric.unlock_tier("Offensive Constructs",1)
eric.unlock_tier("Defensive Constructs",1)
eric.unlock_tier("Offensive Constructs",2)
eric.add_experience(200000)
eric.unlock_tier("Defensive Constructs",2)
eric.unlock_tier("Construct Metamagic",1)
eric.unlock_tier("Construct Metamagic",2)
eric.unlock_tier("Utility Constructs",1)
eric.unlock_tier("Utility Constructs",2)
eric.unlock_tier("Magical Utility",1)
eric.unlock_tier("Magical Utility",2)
eric.add_experience(200000)
eric.add_skill(sk.rammer,10)
eric.add_skill(sk.more_pylons,10)
eric.add_skill(sk.mana_wall,10)
eric.add_skill(sk.intrinsic_clarity(),10) #regen time
eric.add_skill(sk.intrinsic_focus(),10) #now he only has to wake up every two hours instead of 45 minutes, for maximum training
eric.add_skill(sk.magical_synergy(),10)
eric.add_skill(sk.combined_arms,10)
eric.add_skill(sk.tighter_mana_structures,10)
eric.add_skill(sk.mana_bank,10)

eric.unlock_tier("Defensive Constructs",3)
eric.add_skill(sk.stone_tower,10)
eric.add_skill(sk.magic_missile_turret,10)
eric.add_skill(sk.ominous_eye,10)
eric.add_skill(sk.war_banner,10)
eric.add_skill(sk.flexible_design,10)
eric.add_skill(sk.multi_build,10)
eric.add_skill(sk.lamp_post,10)
eric.add_skill(sk.stone_bunker,10)
eric.add_skill(sk.granite_golem,10)
eric.add_skill(sk.mana_manipulation)
eric.add_skill(sk.ice_wall,10)
eric.add_skill(sk.power_station,10)
eric.add_skill(sk.battle_tower,10)

eric.raise_attribute(5, 220)

manaManip = eric.skills["Mana Manipulation"]
manaManip.bank_exp(44)

eric.essence_exhange()

eric.update_vitals()
eric.update_free_attributes()
eric.printCharSheet(altCol= False)
print(eric.vitals)
print(eric.currVitals)
print(eric.general_statistics)